variable "mongo_cluster_id" {
  type        = string
  description = "Resource ID of the parent MongoDB vCore cluster."
  nullable    = false
}

variable "name" {
  type        = string
  description = "Name of the private endpoint connection (matches the connection name generated by Azure)."
  nullable    = false
}

variable "private_link_service_connection_state" {
  type = object({
    status           = string
    description      = optional(string, null)
    actions_required = optional(string, null)
  })
  description = <<DESCRIPTION
Approval state of the private endpoint connection.

- `status`           - (Required) Connection status: 'Approved', 'Pending', or 'Rejected'.
- `description`      - (Optional) Reason for the approval or rejection.
- `actions_required` - (Optional) Message indicating if changes on the service provider require updates on the consumer.
DESCRIPTION
  nullable    = false

  validation {
    condition     = contains(["Approved", "Pending", "Rejected"], var.private_link_service_connection_state.status)
    error_message = "private_link_service_connection_state.status must be 'Approved', 'Pending', or 'Rejected'."
  }
}

variable "enable_telemetry" {
  type        = bool
  default     = true
  description = "Whether to emit AVM telemetry headers. Passed from the root module."
  nullable    = false
}

variable "avm_azapi_header" {
  type        = string
  default     = null
  description = "Pre-computed AVM User-Agent header string from the root module. Pass null when telemetry is disabled."
}
